## --------------------------------------------------------------------------------------------------------------------
# Jekyll
auto: true
exclude: [README.md]

## --------------------------------------------------------------------------------------------------------------------
# Site

title: AppsAttic
tagline: Your Business. Our Apps.
breadcrumbs: 1

## --------------------------------------------------------------------------------------------------------------------
